services:
  tricount-api:
    build: .
    container_name: tricount-api
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - DATA_DIR=/app/data
      - APP_PASSWORD=${APP_PASSWORD}
      - FLASK_DEBUG=0
      - TZ=America/Montreal
    restart: unless-stopped
